#app functionality description:
#show current rankings for top firms in terms of their return momentum
#allow users to input stock ticker and get the stats regarding that company

import pandas as pd
from flask import Flask, render_template, request
app = Flask(__name__)

#get rankings and main data from csv files generated by retrieve_raw_data.py
rankings_df = pd.read_csv('chart_data.csv')
rankings_df.set_index(['Ticker'], inplace=True)
rankings_df.index.name = None
rankings_df = rankings_df.round(decimals=2)
main_df = pd.read_csv('main_data.csv')

#initial home screen
@app.route("/", methods=('POST', 'GET'))
def open():
    top_10_ra = rankings_df.iloc[0:10, :]
    bottom_10_ra = rankings_df.iloc[10:20, :]
    return render_template('home.html', tables=[top_10_ra.to_html(classes='data1'), bottom_10_ra.to_html(classes='data2')], titles=['na', 'Top 10', 'Bottom 10'])

#if you return to home screen
@app.route("/home.html")
def home():
    top_10 = rankings_df.iloc[0:10, :]
    bottom_10 = rankings_df.iloc[10:20, :]
    return render_template('home.html', tables=[top_10.to_html(classes='data1'), bottom_10.to_html(classes='data2')], titles=['na', 'Top 10', 'Bottom 10'])

#about page
@app.route("/about.html")
def about():
    return render_template('about.html')

#initial visit of lookup page
@app.route("/lookup1.html")
def lookup1():
    return render_template('lookup1.html')

#lookup with data, used for viewing results or multiple consecutive lookups
@app.route("/lookup2.html", methods=["POST"])
def lookup2():
    ticker = request.form.get("ticker")
    lookup_df = main_df.loc[main_df['Ticker'] == ticker]
    index = main_df.index[main_df['Ticker'] == ticker]
    lookup_df.set_index(['Ticker'], inplace=True)
    lookup_df.index.name = None
    lookup_df = lookup_df.iloc[:, 1:]
    lookup_df['Percentile'] = 1 - index/len(main_df)
    lookup_df = lookup_df.round(decimals=2)
    length = len(lookup_df)
    return render_template('lookup2.html', length=length, ticker=ticker, tables=[lookup_df.to_html(classes='lookup_data')], titles=['na', 'Search Results:'])

#formulas page
@app.route("/formulas.html")
def formulas():
    return render_template('formulas.html')

if __name__ == "__main__":
    app.run(debug=True)
